import styles from "./Layout.module.scss";
import Head from "next/head";

interface LayoutProps {
  children: React.ReactNode;
  title: string;
  flex?: boolean;
}

const Layout = ({ children, title, flex }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Blog v3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className={styles.header}></div> */}
      <div className={styles.content}>{children}</div>
      {/* <div className={styles.footer}></div> */}
    </>
  );
};

export default Layout;
